// <auto-generated />
using System;
using ChatAgentic.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ChatAgentic.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322145851_AddKnowledgeCreatedAt")]
    partial class AddKnowledgeCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatAgentic.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("identifier");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_contacts_person_id");

                    b.HasIndex("Channel", "Identifier")
                        .HasDatabaseName("ix_contacts_channel_identifier");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<string>("SenderIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sender_identifier");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("WorkspaceId", "Channel", "SenderIdentifier")
                        .HasDatabaseName("ix_conversations_workspace_id_channel_sender_identifier");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.ConversationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content_text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("file_name");

                    b.Property<string>("MediaUri")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("media_uri");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_conversation_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_conversation_messages_conversation_id");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.Knowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("VECTOR(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_knowledges");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledges_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "HNSW");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("WorkspaceId", "Context")
                        .HasDatabaseName("ix_knowledges_workspace_id_context");

                    b.ToTable("knowledges", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_people_workspace_id");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("webhook_token");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("WebhookToken")
                        .HasDatabaseName("ix_workspaces_webhook_token");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Entities.Contact", b =>
                {
                    b.HasOne("ChatAgentic.Entities.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Conversation", b =>
                {
                    b.HasOne("ChatAgentic.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ChatAgentic.Entities.ConversationMessage", b =>
                {
                    b.HasOne("ChatAgentic.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_messages_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Knowledge", b =>
                {
                    b.HasOne("ChatAgentic.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledges_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Person", b =>
                {
                    b.HasOne("ChatAgentic.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_people_workspaces_workspace_id");

                    b.OwnsMany("ChatAgentic.Entities.PersonMetadataItem", "Metadata", b1 =>
                        {
                            b1.Property<int>("PersonId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("PersonId", "__synthesizedOrdinal");

                            b1.ToTable("people");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_people_people_person_id");
                        });

                    b.Navigation("Metadata");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Workspace", b =>
                {
                    b.OwnsOne("ChatAgentic.Entities.WorkspaceMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("WorkspaceId");

                            b1.Property<string>("ChatModel");

                            b1.Property<string>("EmbedModel");

                            b1.Property<string>("ProviderApiKey");

                            b1.Property<string>("ProviderUrl");

                            b1.Property<int>("SchemaVersion");

                            b1.PrimitiveCollection<string>("Tools");

                            b1.Property<string>("TranscriptionModel");

                            b1.Property<string>("TtsModel");

                            b1.Property<string>("TtsVoice");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");
                        });

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ChatAgentic.Entities.Person", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
