// <auto-generated />
using ChatAgentic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatAgentic.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatAgentic.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("webhook_token");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("WebhookToken")
                        .HasDatabaseName("ix_workspaces_webhook_token");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("ChatAgentic.Models.Workspace", b =>
                {
                    b.OwnsOne("ChatAgentic.Models.WorkspaceMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("WorkspaceId");

                            b1.Property<string>("ChatModel");

                            b1.Property<string>("EmbedModel");

                            b1.Property<string>("ProviderApiKey");

                            b1.Property<string>("ProviderUrl");

                            b1.Property<int>("SchemaVersion");

                            b1.PrimitiveCollection<string>("Tools");

                            b1.Property<string>("TranscriptionModel");

                            b1.Property<string>("TtsModel");

                            b1.Property<string>("TtsVoice");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
